#--------------------------------------------------------------
# EMR Security COnfiguration
#--------------------------------------------------------------

variable "security_configuration_name" {
  type        = string
  default     = ""
  description = "(Optional) The name of the EMR Security Configuration. By default generated by Terraform."
}

variable "name_prefix" {
  type        = string
  default     = null
  description = "(Optional) Creates a unique name beginning with the specified prefix. Conflicts with name."
}

variable "configuration" {
  type        = string
  default     = ""
  description = "(Required) A JSON formatted Security Configuration"
}

variable "encryption_at_rest" {
  type        = bool
  default     = false
  description = "Specify true to enable at-rest encryption and false to disable it. If omitted, false is assumed and at-rest encryption is disabled."
}

variable "encryption_in_transit" {
  type        = bool
  default     = false
  description = "Specify true to enable in-transit encryption and false to disable it. If omitted, false is assumed, and in-transit encryption is disabled."
}

variable "s3_encryption_at_rest_mode" {
  type        = string
  default     = "SSE-S3"
  description = "Specifies the type of Amazon S3 encryption to use. If SSE-S3 is specified, no further Amazon S3 encryption values are required. If either SSE-KMS or CSE-KMS is specified, an AWS KMS customer master key (CMK) ARN must be specified as the AwsKmsKey value. If CSE-Custom is specified, S3Object and EncryptionKeyProviderClass values must be specified."
}

variable "disk_encryption_at_rest_type" {
  type        = string
  default     = null
  description = "Specifies the key provider for local disk encryption. If AwsKms is specified, an AWS KMS CMK ARN must be specified as the AwsKmsKey value. If Custom is specified, S3Object and EncryptionKeyProviderClass values must be specified."
}

variable "encryption_at_rest_disk_key" {
  type        = string
  default     = null
  description = "Required only when 'disk_encryption_at_rest_type' is specified for Type. MyKeyARN must be a fully specified ARN to a key"
}
