#--------------------------------------------------------------
# EMR
#--------------------------------------------------------------

variable "emr_cluster_id" {
  type        = string
  description = "Id the target EMR cluster to use as event source"
}

#--------------------------------------------------------------
# Cloudwatch Event Rule
#--------------------------------------------------------------

variable "event_rule_name" {
  type        = string
  default     = null
  description = "(Optional) The rule's name. By default generated by Terraform."
}

variable "event_rule_name_prefix" {
  type        = string
  default     = null
  description = "(Optional) The rule's name. Conflicts with name."
}

variable "event_rule_schedule_expression" {
  type        = string
  default     = null
  description = "(Required, if event_pattern isn't specified) The scheduling expression. For example, cron(0 20 * * ? *) or rate(5 minutes)."
}

variable "event_rule_event_pattern" {
  type        = string
  default     = null
  description = "(Required, if schedule_expression isn't specified) Event pattern described a JSON object."
}

variable "event_rule_description" {
  type        = string
  default     = null
  description = "(Optional) The description of the rule."
}

variable "event_rule_role_arn" {
  type        = string
  default     = null
  description = "(Optional) The Amazon Resource Name (ARN) associated with the role that is used for target invocation."
}

variable "event_rule_is_enabled" {
  type        = bool
  default     = true
  description = "(Optional) Whether the rule should be enabled (defaults to true)."
}

#--------------------------------------------------------------
# Cloudwatch Event Target
#--------------------------------------------------------------

variable "event_target_rule" {
  type        = string
  description = "(Required) The name of the rule you want to add targets to."
}

variable "event_target_target_id" {
  type        = string
  default     = null
  description = "(Optional) The unique target assignment ID. If missing, will generate a random, unique id."
}

variable "event_target_arn" {
  type        = string
  description = "(Required) The Amazon Resource Name (ARN) associated of the target."
}

variable "event_target_input" {
  type        = string
  default     = null
  description = "(Optional) Valid JSON text passed to the target."
}

variable "event_target_input_path" {
  type        = string
  default     = null
  description = "(Optional) The value of the JSONPath that is used for extracting part of the matched event when passing it to the target."
}

variable "event_target_role_arn" {
  type        = string
  default     = null
  description = "(Optional) The Amazon Resource Name (ARN) of the IAM role to be used for this target when the rule is triggered. Required if ecs_target is used."
}

variable "event_target_run_command_targets" {
  type        = list(any)
  default     = []
  description = "(Optional) Parameters used when you are using the rule to invoke Amazon EC2 Run Command. Documented below. A maximum of 5 are allowed."
}

variable "event_target_ecs_target" {
  type        = list(any)
  default     = []
  description = "(Optional) Parameters used when you are using the rule to invoke Amazon ECS Task. Documented below. A maximum of 1 are allowed."
}

variable "event_target_batch_target" {
  type        = list(any)
  default     = []
  description = "(Optional) Parameters used when you are using the rule to invoke an Amazon Batch Job. Documented below. A maximum of 1 are allowed."
}

variable "event_target_kinesis_target" {
  type        = list(any)
  default     = []
  description = "(Optional) Parameters used when you are using the rule to invoke an Amazon Kinesis Stream. Documented below. A maximum of 1 are allowed."
}

variable "event_target_sqs_target" {
  type        = list(any)
  default     = []
  description = "(Optional) Parameters used when you are using the rule to invoke an Amazon SQS Queue. Documented below. A maximum of 1 are allowed."
}

variable "event_target_input_transformer" {
  type        = list(any)
  default     = []
  description = "(Optional) Parameters used when you are providing a custom input to a target based on certain event data."
}
